version: '3'
services:
  portainer:
    image: portainer/portainer
    networks:
      - default
    restart: always
#    ports:
#      - "9000:9000"
    expose:
      - 9000
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_HOST: portainer.local
      LETSENCRYPT_HOST: portainer.local
      LETSENCRYPT_EMAIL: security@brosy.com

volumes:
  portainer_data:

networks:
  default:
    external:
      name: nginx-proxy
